# Generated by Django 3.2.5 on 2021-07-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_publishing_house_book_publushing_house'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publushing_house',
            new_name='publishing_house',
        ),
    ]
